services:
  postgres:
    image: postgres:latest
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - .env
    networks:
      - shared_network

  user_service:
    build:
      context: ./backend/user_service
      dockerfile: Dockerfile
    container_name: user_service
    # labels:
    #     co.elastic.logs/module: "django"
    ports:
      - "8010:8010"
    volumes:
      - certs:/certs
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    restart: always
    networks:
      - shared_network

  nginx:
    image: nginx:latest
    container_name: nginx
    # labels:
    #     co.elastic.logs/module: "nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
      - certs:/etc/nginx/certs
    command: /bin/bash -c "nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - user_service
    env_file:
      - .env
    # logging:
    #     driver: "json-file"
    networks:
      - shared_network
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - shared_network
    restart: always
volumes:
  postgres_data:
    name: postgres_data
    driver: local
  certs:
    external: true

networks:
  shared_network:
    name: shared_network
    external: true
