# Generated by Django 5.2.1 on 2025-06-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='two_factor_Auth',
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_auth',
            field=models.CharField(default=False),
        ),
    ]
