# Generated by Django 5.2.4 on 2025-07-08 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtable',
            name='username1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchtable',
            name='username2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchtable',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
