# Generated by Django 5.2.3 on 2025-06-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_two_factor_auth_user_two_factor_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='MATCHTABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchKey', models.CharField(max_length=100, unique=True)),
                ('username1', models.CharField(max_length=100)),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('username2', models.CharField(max_length=100)),
            ],
        ),
    ]
