# Generated by Django 5.2.3 on 2025-06-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_matchtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtable',
            name='username1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='matchtable',
            name='username2',
            field=models.CharField(max_length=15),
        ),
    ]
