# Generated by Django 5.2.3 on 2025-06-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_matchtable_username1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='imgs/default.png', max_length=255),
        ),
    ]
