# Generated by Django 5.2.1 on 2025-05-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('two_factor_Auth', models.CharField(max_length=255)),
                ('online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.ImageField(default='imgs/default.png', upload_to='imgs/')),
            ],
        ),
    ]
