# Generated by Django 5.2.1 on 2025-05-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_mail_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_factor_Auth',
            field=models.CharField(default=False),
        ),
    ]
