# Generated by Django 4.2.20 on 2025-06-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_two_factor_auth_user_two_factor_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_factor_auth',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
