# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decoder.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdecoder.proto\x12\njwtdecoder\"\x1b\n\njwtRequest\x12\r\n\x05\x63oded\x18\x01 \x01(\t\"\x1e\n\x0bjwtResponse\x12\x0f\n\x07\x64\x65\x63oded\x18\x01 \x01(\t2G\n\x07Greeter\x12<\n\tdecodeJWT\x12\x16.jwtdecoder.jwtRequest\x1a\x17.jwtdecoder.jwtResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'decoder_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JWTREQUEST._serialized_start=29
  _JWTREQUEST._serialized_end=56
  _JWTRESPONSE._serialized_start=58
  _JWTRESPONSE._serialized_end=88
  _GREETER._serialized_start=90
  _GREETER._serialized_end=161
# @@protoc_insertion_point(module_scope)
