api.http.host: "0.0.0.0"
# xpack.security.enabled: true
# xpack.security.http.ssl.enabled: true
# xpack.security.http.ssl.key: "/usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.key"
# xpack.security.http.ssl.certificate: "/usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.crt"
# xpack.security.http.ssl.certificate_authorities: "/usr/share/elasticsearch/config/certs/ca/ca.crt"
# xpack.security.transport.ssl.enabled: true
# xpack.security.transport.ssl.key: "/usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.key"
# xpack.security.transport.ssl.certificate: "/usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.crt"
# xpack.security.transport.ssl.certificate_authorities: "/usr/share/elasticsearch/config/certs/ca/ca.crt"
# xpack.security.transport.ssl.verification_mode: certificate

# xpack.monitoring.enabled: false
log.level: info
xpack.monitoring.elasticsearch.hosts: ["https://elasticsearch:9200"]
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.ssl.certificate_authority: "/usr/share/logstash/config/certs/ca/ca.crt"
xpack.monitoring.elasticsearch.username: "logstash_system"
xpack.monitoring.elasticsearch.password: "jJkJ_p7EwHa0k+EgBgNW"
config.reload.automatic: false
path.logs: "/usr/share/logstash/logs"
path.data: "/usr/share/logstash/data"
path.config: "/usr/share/logstash/config"

pipeline.id: "main"
pipeline.workers: 2 # Or the number of CPU cores you want to dedicate
pipeline.batch.size: 125
pipeline.batch.delay: 50
pipeline.buffer.type: heap
pipeline.ordered: auto
